"""Sync the o-spreadsheet source repo to the runtime's stable branch.

The Odoo `spreadsheet` addon ships a bundled / minified copy of o-spreadsheet
under `odoo/addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js`. The
bundle is grep-able but minified — readable but missing comments, JSDoc, and
tests.

The actual source lives at https://github.com/odoo/o-spreadsheet, with stable
branches per Odoo major (`17.0`, `18.0`, `19.0`, ...). This script:

  1. Detects the runtime's o-spreadsheet semver by reading the JSDoc `@version`
     header of the bundle (e.g. `19.0.32`).
  2. Maps it to the stable branch — `<major>.0`, e.g. `19.0`.
  3. Clones the source repo to `skills/odoo-spreadsheet-report/reference/o-spreadsheet-source/`
     on first run (partial clone, `--filter=blob:none`).
  4. Fetches + checks out the matching stable branch on subsequent runs.
  5. Reports the local path + detected semver + checked-out branch so the
     agent can grep it as the authoritative reference.

Usage:
    # Auto-detect runtime + sync to the matching stable branch
    python3 _sync_o_spreadsheet_source.py

    # Force a specific branch (e.g. cross-version investigation)
    python3 _sync_o_spreadsheet_source.py --branch 18.0

    # Just print what would happen
    python3 _sync_o_spreadsheet_source.py --dry-run
"""
import argparse
import json
import re
import subprocess
import sys
from pathlib import Path


REPO_URL = "https://github.com/odoo/o-spreadsheet.git"


def find_repo_root(start: Path) -> Path:
    cur = start.resolve()
    for _ in range(10):
        if all((cur / d).is_dir() for d in ("odoo", "enterprise", "skills")):
            return cur
        if cur.parent == cur:
            break
        cur = cur.parent
    raise RuntimeError(f"Could not locate repo root above {start}")


def detect_runtime_version(repo_root: Path) -> str | None:
    """Return the bundle's full semver from its JSDoc `@version` header.

    The header looks like:

        /**
         * This file is generated by o-spreadsheet build tools. Do not edit it.
         * @see https://github.com/odoo/o-spreadsheet
         * @version 19.0.32
         * @date 2026-05-07T11:01:50.766Z
         */

    Greping for arbitrary "version" literals in the bundle is unsafe — the
    minified code contains many migration-target literals (`"15.4.1"`,
    `"18.5.1"`, ...) that have nothing to do with the bundle's own version.
    """
    bundle = repo_root / "odoo/addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js"
    if not bundle.is_file():
        return None
    try:
        # Only need the header; reading the first 4 KB is plenty.
        with bundle.open("r", errors="replace") as f:
            head = f.read(4096)
    except Exception:
        return None
    m = re.search(r"@version\s+(\d+\.\d+\.\d+)", head)
    if m:
        return m.group(1)
    # Fallbacks for older bundle formats.
    text = bundle.read_text(errors="replace")
    for pat in (
        r"CURRENT_VERSION\s*=\s*['\"](\d+\.\d+\.\d+)['\"]",
        r"const\s+CURRENT_VERSION\s*=\s*['\"](\d+\.\d+\.\d+)['\"]",
    ):
        m = re.search(pat, text)
        if m:
            return m.group(1)
    return None


def stable_branch_for(semver: str) -> str:
    """Map a full semver to its o-spreadsheet stable branch name.

    >>> stable_branch_for("19.0.32")
    '19.0'
    >>> stable_branch_for("18.5.10")
    '18.0'
    """
    major = semver.split(".", 1)[0]
    return f"{major}.0"


def run(cmd: list[str], cwd: Path | None = None, capture: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, cwd=cwd, capture_output=capture, text=True, timeout=300)


def clone_or_fetch(target: Path, dry_run: bool) -> None:
    if target.is_dir() and (target / ".git").is_dir():
        print(f"  Existing clone at {target} — fetching tags")
        if not dry_run:
            r = run(["git", "fetch", "--tags", "origin"], cwd=target)
            if r.returncode != 0:
                raise SystemExit(f"git fetch failed: {r.stderr}")
        return
    print(f"  Cloning {REPO_URL} into {target}")
    if not dry_run:
        target.parent.mkdir(parents=True, exist_ok=True)
        r = run(["git", "clone", "--filter=blob:none", REPO_URL, str(target)])
        if r.returncode != 0:
            raise SystemExit(f"git clone failed: {r.stderr}")


def checkout_branch(target: Path, branch: str, dry_run: bool) -> str:
    """Check out the requested stable branch (e.g. '19.0'). Returns the ref string."""
    print(f"  Checking out branch {branch}")
    if dry_run:
        return branch
    r = run(["git", "rev-parse", "--verify", f"origin/{branch}"], cwd=target)
    if r.returncode != 0:
        raise SystemExit(
            f"Stable branch {branch!r} not found on {REPO_URL}. "
            "Pass --branch <name> to override."
        )
    ref = f"origin/{branch}"
    r = run(["git", "checkout", "--detach", ref], cwd=target)
    if r.returncode != 0:
        raise SystemExit(f"git checkout {ref} failed: {r.stderr}")
    head = run(["git", "rev-parse", "--short", "HEAD"], cwd=target).stdout.strip()
    return f"{ref} ({head})"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--branch", default=None,
                    help="Force a specific stable branch (e.g. 19.0, 18.0). "
                         "Default: derive from the runtime semver.")
    ap.add_argument("--dry-run", action="store_true",
                    help="Print actions without executing them.")
    ap.add_argument("--target", default=None,
                    help="Override the local clone path "
                         "(default: skills/odoo-spreadsheet-report/reference/o-spreadsheet-source).")
    args = ap.parse_args()

    repo_root = find_repo_root(Path(__file__).parent)
    target = Path(args.target) if args.target else (
        repo_root / "skills/odoo-spreadsheet-report/reference/o-spreadsheet-source"
    )

    semver = detect_runtime_version(repo_root)
    branch = args.branch or (stable_branch_for(semver) if semver else None)
    if not branch:
        raise SystemExit(
            "Could not detect runtime o-spreadsheet version from the bundle. "
            "Pass --branch <name> (e.g. 19.0) explicitly."
        )

    print(f"--- o-spreadsheet source sync")
    print(f"  runtime semver  : {semver or '(unknown)'}")
    print(f"  stable branch   : {branch}")
    print(f"  target dir      : {target}")
    print(f"  remote          : {REPO_URL}")

    clone_or_fetch(target, args.dry_run)
    checked_out = checkout_branch(target, branch, args.dry_run)

    summary = {
        "target": str(target),
        "runtime_semver": semver,
        "stable_branch": branch,
        "checked_out": checked_out,
        "src_dir": str(target / "src") if (target / "src").is_dir() else str(target),
    }
    print()
    print("--- Result")
    print(json.dumps(summary, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
